version: "2.1"
services:
  mysql:
    build: ./database
    user: "${UID}"
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 60

  aria2:
    image: hobbsau/aria2 
    user: "${UID}"
    volumes:
      - ${STORAGE_DIR}:/downloads
      - ${CONFIG_DIR}/aria2:/home/aria2
    network_mode: host
    restart: always

  transmission:
    image: linuxserver/transmission
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${STORAGE_DIR}:/downloads
    environment:
      - PUID=${UID}
      - PGID=${GID}
    network_mode: host
    restart: always

  cms:
    image: lixiaocong/lxccms
    user: "${UID}"
    volumes:
      - ${STORAGE_DIR}:/storage
      - ${CONFIG_DIR}:/config
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
      - APPLICATION_URL=${APPLICATION_URL}
      - QQ_ID=${QQ_ID}
      - QQ_SECRET=${QQ_SECRET}
      - WEIXIN_ID=${WEIXIN_ID}
      - WEIXIN_SECRET=${WEIXIN_SECRET}
      - WEIXIN_TOKEN=${WEIXIN_TOKEN}
      - WEIXIN_KEY=${WEIXIN_KEY}
    network_mode: host
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:1.13
    user: "${UID}"
    volumes:
      - ${CONFIG_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${STORAGE_DIR}:/storage
    network_mode: host
    restart: always
