version: "2.1"
services:

  cmsdb:
    build: ./database
    user: "${UID}"
    network_mode: host
    volumes:
      - ${CONFIG_DIR}/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 60

  aria2:
    image: hobbsau/aria2
    user: "${UID}"
    volumes:
      - ${STORAGE_DIR}:/downloads
      - ${CONFIG_DIR}/aria2:/home/aria2
    network_mode: host
    restart: always

  transmission:
    image: linuxserver/transmission:100
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${STORAGE_DIR}:/downloads
    environment:
      - PUID=${UID}
      - PGID=${GID}
    network_mode: host
    restart: always

  cms:
    image: lixiaocong/lxccms
    user: "${UID}"
    volumes:
      - ${STORAGE_DIR}:/downloads
      - ${CONFIG_DIR}:/config
    network_mode: host
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:1.13
    user: "${UID}"
    volumes:
      - ${CONFIG_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${STORAGE_DIR}:/downloads
    network_mode: host
    restart: always
