version: "3"
services:
  cms:
    image: lixiaocong/lxccms
    ports:
      - ${LXCCMS_PORT}:8080
    environment:
      DB_HOST: ${LXCDB_HOST} 
      DB_PORT: ${LXCDB_PORT}
      DB_USERNAME: ${LXCDB_USERNAME}
      DB_PASSWD: ${LXCDB_PASSWD}
      REDIS_HOST: ${LXCREDIS_HOST}
      REDIS_PORT: ${LXCREDIS_PORT}
    restart: always