version: "2.1"
services:

  cmsdb:
    image: mysql:5.7
    user: "${UID}"
    volumes:
      - ${CONFIG_DIR}/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ${CONFIG_DIR}/db/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ${STORAGE_DIR}/cms_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:`
      - 3306:3306

  aria2:
    image: hobbsau/aria2
    user: "${UID}"
    volumes:
      - ${STORAGE_DIR}/downloads:/downloads
      - ${CONFIG_DIR}/aria2:/home/aria2
    ports:
      - 6800:6800

  transmission:
    image: linuxserver/transmission:100
    volumes:
      - ${STORAGE_DIR}/downloads:/downloads
      - ${CONFIG_DIR}/transmission:/config
    environment:
      - PUID=${UID}
      - PGID=${GID}
    ports:
      - 9091:9091
  
  redis:
    image: redis:5.0-rc4
    ports:
      - 6379:6379
