version: "2.1"
services:

  cmsdb:
    build: ../database
    user: "${UID}"
    volumes:
      - ${CONFIG_DIR}/data:/var/lib/mysql
    ports:
      - 3306:3306

  aria2:
    image: hobbsau/aria2
    user: "${UID}"
    volumes:
      - ${STORAGE_DIR}:/downloads
      - ${CONFIG_DIR}/aria2:/home/aria2
    ports:
      - 6800:6800

  transmission:
    image: linuxserver/transmission:100
    volumes:
      - ${STORAGE_DIR}:/downloads
      - ${CONFIG_DIR}/transmission:/config
    environment:
      - PUID=${UID}
      - PGID=${GID}
    ports:
      - 9091:9091
  
  redis:
    image: redis:5.0-rc4
    ports:
      - 6379:6379