version: "2.1"
services:

  cmsdb:
    build: ../database
    user: "${UID}"
    ports:
      - 3306:3306

  aria2:
    image: hobbsau/aria2
    user: "${UID}"
    volumes:
      - ${STORAGE_DIR}:/downloads
      - ${CONFIG_DIR}/aria2:/home/aria2
    ports:
      - 6800:6800

  transmission:
    image: linuxserver/transmission:100
    volumes:
      - ${STORAGE_DIR}:/downloads
      - ${CONFIG_DIR}/transmission:/config
    environment:
      - PUID=${UID}
      - PGID=${GID}
    ports:
      - 9091:9091

  # only works for Linux
  nginx:
    image: nginx:1.13
    user: "${UID}"
    volumes:
      - ${STORAGE_DIR}:/downloads
      - ${CONFIG_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${CONFIG_DIR}/nginx/ariaNG:/ariaNG
    network_mode: host
